# Generated by Django 3.0.5 on 2023-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('registration_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('registration_date', models.DateField(null=True)),
                ('license_plate', models.CharField(max_length=20, null=True)),
                ('registered_location', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('engine_capacity', models.FloatField(null=True)),
                ('power', models.FloatField(null=True)),
                ('torque', models.FloatField(null=True)),
                ('transmission', models.CharField(max_length=50, null=True)),
                ('seating_capacity', models.PositiveIntegerField(null=True)),
                ('length', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('fuel_consumption', models.FloatField(null=True)),
                ('suspension', models.CharField(max_length=100, null=True)),
                ('braking_system', models.CharField(max_length=100, null=True)),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('owner', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
