# Generated by Django 3.0.5 on 2023-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_auto_20230525_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinspection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='id',
        ),
        migrations.AlterField(
            model_name='carinspection',
            name='inspection_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='owner_code',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
