# Generated by Django 3.0.5 on 2023-06-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_auto_20230601_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinspection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Car.CarOwner'),
        ),
    ]
